services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: MyMusicCollection
    ports:
      - 5432
    volumes:
      - music_postgres_data:/var/lib/postgresql
    networks:
      - traefik-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  music-api:
    build:
      context: ./MusicApi
      dockerfile: Dockerfile
    ports:
      - 5550
    environment:
      - ASPNETCORE_URLS=http://+:5550
    depends_on:
      postgres:
        condition: service_healthy
      music-api-migrate:
        condition: service_completed_successfully
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.music-api.rule=PathPrefix(`/`)"
      - "traefik.http.routers.music-api.entrypoints=music-api"
      - "traefik.http.services.music-api.loadbalancer.server.port=5550"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik-net
    volumes:
      - music_api_images:/app/uploads
    restart: unless-stopped

  music-api-migrate:
    build:
      context: ./MusicApi
      dockerfile: Dockerfile.migrate
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Server=${POSTGRES_HOST:-postgres};Database=MyMusicCollection;User Id=${POSTGRES_USER:-postgres};Password=${POSTGRES_PASSWORD:-postgres};
    networks:
      - traefik-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  music-ui:
    build:
      context: ./music-ui
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BASE_URL=${MUSIC_API_BASE_URL:-http://localhost:5550}
    ports:
      - 5501
    depends_on:
      - music-api
    environment:
      - PORT=5501
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.music-ui.rule=PathPrefix(`/`)"
      - "traefik.http.routers.music-ui.entrypoints=music-ui"
      - "traefik.http.services.music-ui.loadbalancer.server.port=5501"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
    networks:
      - traefik-net

  traefik:
    image: traefik
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker"
      - "--log.level=DEBUG"
      - "--entrypoints.music-api.address=:5550"
      - "--entrypoints.music-ui.address=:5501"
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/access.log"
    ports:
      - "8080:8080" # Dashboard
      - "5501:5501" # Music UI
      - "5550:5550" # Music API
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./traefik-logs:/var/log" # Mount a directory for log files
    restart: unless-stopped
    networks:
      - traefik-net

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 300
    restart: unless-stopped
    networks:
      - traefik-net

volumes:
  music_postgres_data:
  music_api_images:


networks:
  traefik-net:
    driver: bridge
