services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: MyMusicCollection
    ports:
      - "5432:5432"
    volumes:
      - music_postgres_data:/var/lib/postgresql
volumes:
  music_postgres_data:
