FROM mcr.microsoft.com/dotnet/sdk:9.0 AS migrate
WORKDIR /src
COPY . .
RUN dotnet tool install --global dotnet-ef --version '9.0.0-*'
ENV PATH="$PATH:/root/.dotnet/tools"
CMD ["dotnet", "ef", "database", "update"]