### Get Music
@MusicApi_HostAddress = http://localhost:5550
@BasicAuth_Username = user
@BasicAuth_Password = password123

GET {{MusicApi_HostAddress}}/api/music
Accept: application/json

### Create Music
POST {{MusicApi_HostAddress}}/api/music
Content-Type: application/json
Headers:
Authorization: Basic {{BasicAuth_Username}}:{{BasicAuth_Password}}

{
    "Title": "Memory2",
    "Artist": "Love",
    "ReleaseDate": "2023-10-01T00:00:00Z"
}

### Get Albums
GET {{MusicApi_HostAddress}}/api/albums
Accept: application/json

### Get Album
GET {{MusicApi_HostAddress}}/api/albums/f0ca3e65-4984-4cfd-9fb0-6de4ca21fe95
Accept: application/json