### Get Music
@MusicApi_HostAddress = http://localhost:5191

GET {{MusicApi_HostAddress}}/api/music
Accept: application/json

### Create Music
POST {{MusicApi_HostAddress}}/api/music
Content-Type: application/json

{
    "Title": "Memory2",
    "Artist": "Love",
    "ReleaseDate": "2023-10-01T00:00:00Z"
}

### Create Album
Post {{MusicApi_HostAddress}}/api/albums
Content-Type: application/json

{
    "Title": "Album1",
    "Artist": "Band",
    "ReleaseDate": "2023-10-01T00:00:00Z"
}