name: automation
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pwd
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "9.0.x"
      - name: Install dependencies
        run: dotnet restore MusicApi/MusicApi.csproj
      - name: Build
        run: dotnet build --no-restore MusicApi/MusicApi.csproj --configuration Release --verbosity minimal
      - name: Run EF Core Migrations
        run: |
          cd MusicApi
          dotnet tool install --global dotnet-ef
          export PATH="$PATH:/home/runner/.dotnet/tools"
          dotnet ef database update --project MusicApi.csproj --context AppDbContext --connection "Host=localhost;Port=5432;Database=postgres;Username=postgres;Password=pwd"
      # - name: Test
      #   run: dotnet test --no-build --verbosity normal MusicApi.Tests/MusicApi.Tests.csproj
